document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title></title>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/footer.css\'/>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/normalize_zh.css\'/>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!--尾部开始-->");
document.writeln("		<footer>");
document.writeln("		    <div class=\'aboutBG\'>");
document.writeln("		        <div class=\'about\'>");
document.writeln("		            <div class=\'policy\'>");
document.writeln("		                <ul>");
document.writeln("		                    <li>");
document.writeln("		                        <i>&#xe62e;</i>预约维修服务");
document.writeln("		                    </li>");
document.writeln("		                    <li>");
document.writeln("		                        <i>&#xe606;</i>7天无理由退货");
document.writeln("		                    </li>");
document.writeln("		                    <li>");
document.writeln("		                        <i>&#xe607;</i>15天免费换货");
document.writeln("		                    </li>");
document.writeln("		                    <li>");
document.writeln("		                        <i>&#xe639;</i>满150元包邮");
document.writeln("		                    </li>");
document.writeln("		                    <li>");
document.writeln("		                        <i>&#xe64c;</i>520余家售后网点");
document.writeln("		                    </li>");
document.writeln("		                </ul>");
document.writeln("		                <div class=\'survey\'>");
document.writeln("		                    <dl>");
document.writeln("		                        <dt>帮助中心</dt>");
document.writeln("		                        <dd><a href=\'#\'>账户管理</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>购物指南</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>订单操作</a></dd>");
document.writeln("		                    </dl>");
document.writeln("		                    <dl>");
document.writeln("		                        <dt>服务支持</dt>");
document.writeln("		                        <dd><a href=\'#\'>售后政策</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>自助服务</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>相关下载</a></dd>");
document.writeln("		                    </dl>");
document.writeln("		                    <dl>");
document.writeln("		                        <dt>线下门店</dt>");
document.writeln("		                        <dd><a href=\'#\'>小米之家</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>服务网点</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>零售网点</a></dd>");
document.writeln("		                    </dl>");
document.writeln("		                    <dl>");
document.writeln("		                        <dt>关于小米</dt>");
document.writeln("		                        <dd><a href=\'#\'>了解小米</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>加入小米</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>联系我们</a></dd>");
document.writeln("		                    </dl>");
document.writeln("		                    <dl>");
document.writeln("		                        <dt>关注我们</dt>");
document.writeln("		                        <dd><a href=\'#\'>新浪微博</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>小米部落</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>官方微信</a></dd>");
document.writeln("		                    </dl>");
document.writeln("		                    <dl>");
document.writeln("		                        <dt>特色服务</dt>");
document.writeln("		                        <dd><a href=\'#\'>F码通道</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>礼物码</a></dd>");
document.writeln("		                        <dd><a href=\'#\'>防伪查询</a></dd>");
document.writeln("		                    </dl>");
document.writeln("		                    <div class=\'contact\'>");
document.writeln("		                        <h2>400-100-5678</h2>");
document.writeln("		                        <p>周一至周日 8:00-18:00<br>仅收市话费</p>");
document.writeln("		                        <span><i>&#xe60e;</i>24小时在线客服</span>");
document.writeln("		                    </div>");
document.writeln("		                </div>");
document.writeln("		            </div>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		    <div class=\'copy\'>");
document.writeln("		        <div class=\'bottomLogo\'><img src=\'images/12-底部/logo-footer.png\' alt=\'logo\'></div>");
document.writeln("		        <div class=\'link\'>");
document.writeln("		            <a href=\'#\'>小米商城</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>MIUI</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>米聊</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>多看书城</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>小米路由器</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>视频电话</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>企业团购</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>小米天猫店</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>小米淘宝直营店</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>小米网盟</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>小米移动</a>");
document.writeln("		            |");
document.writeln("		            <a href=\'#\'>Select Region</a>");
document.writeln("		            <br>");
document.writeln("		            &copymi.com 京ICP证110507号 京ICP备10046444号 京公网安备11010802020134 京网文[2014]0059-0009号");
document.writeln("		            <br>");
document.writeln("		            违法和不良信息举报电话：186-0130-1238，本网站所列数据，除特殊说明，所有数据均出自我司实验室测试");
document.writeln("		        </div>");
document.writeln("		        <div class=\'verify\'>");
document.writeln("		            <img src=\'images/12-底部/truste.png\' alt=\'\'>");
document.writeln("		            <img src=\'images/12-底部/v-logo-1.png\' alt=\'\'>");
document.writeln("		            <img src=\'images/12-底部/v-logo-2.png\' alt=\'\'>");
document.writeln("		            <img src=\'images/12-底部/v-logo-3.png\' alt=\'\'>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("		    <div class=\'slogan\'><img src=\'images/12-底部/slogan2016.png\' alt=\'\'></div>");
document.writeln("		</footer>");
document.writeln("		<!--尾部结束-->");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");