document.writeln("<!DOCTYPE html>");
document.writeln("<html>");
document.writeln("	<head>");
document.writeln("		<meta charset=\'utf-8\'>");
document.writeln("		<title></title>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/header.css\'/>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/normalize_zh.css\'/>");
document.writeln("	</head>");
document.writeln("	<body>");
document.writeln("		<!--头部开始-->");
document.writeln("	");
document.writeln("		    <div class=\'topBanner\'></div>");
document.writeln("		    <div class=\'nav\'>");
document.writeln("		        <div class=\'navCenter\'>");
document.writeln("		            <ul>");
document.writeln("		                <li><a href=\'#\'>小米商城</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>MIUI</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>米聊</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>游戏</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>多看阅读</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>云服务</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>金融</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>小米商城移动版</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>问题反馈</a><span>|</span></li>");
document.writeln("		                <li><a href=\'#\'>Select Region</a></li>");
document.writeln("		            </ul>");
document.writeln("		            <div class=\'login\'>");
document.writeln("		                <ul>");
document.writeln("		                    <li><a href=\'xm/public/login.html\'>登录<span>|</span></a></li>");
document.writeln("		                    <li><a href=\'xm/public/register.html\'>注册</a><span>|</span></li>");
document.writeln("		                    <li><a href=\'#\'>消息通知</a></li>");
document.writeln("		                </ul>");
document.writeln("		                <div class=\'shoppingCart\'>");
document.writeln("		                    <i>&#xe61b;</i>购物车( 0 )");
document.writeln("		                </div>");
document.writeln("		            </div>");
document.writeln("		        </div>");
document.writeln("		    </div>");
document.writeln("");
document.writeln("		<!--头部结束-->");
document.writeln("		<div class=\'logoNav\'>");
document.writeln("		    <div class=\'logo\'><img src=\'images/1-top/logo.jpg\'></div>");
document.writeln("		    <ul class=\'logo-nav\'>");
document.writeln("		        <li>");
document.writeln("					<a href=\'#\'>小米手机</a>");
document.writeln("					<div class=\'xiaomi\'>");
document.writeln("						<div class=\'xiaomi-1\'>");
document.writeln("							<ul>");
document.writeln("								<li>");
document.writeln("									<a href=\'mi9.html\'><img class=\'xiaomi-cc9\' src=\'images/6-配件/_320.png\' alt=\'\'></a>");
document.writeln("									<p><a href=\'mi9.html\'>小米CC9</a></p>");
document.writeln("									<p class=\'price-cc9\'>1799元起</p>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'mix3.html\'><img class=\'xiaomi-cc9\' src=\'images/6-配件/_320.png\' alt=\'\'></a>");
document.writeln("									<p><a href=\'mix3.html\'>小米CC9</a></p>");
document.writeln("									<p class=\'price-cc9\'>1799元起</p>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'mi9.html\'><img class=\'xiaomi-cc9\' src=\'images/6-配件/_320.png\' alt=\'\'></a>");
document.writeln("									<p><a href=\'mix3.html\'>小米CC9</a></p>");
document.writeln("									<p class=\'price-cc9\'>1799元起</p>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'mi9.html\'><img class=\'xiaomi-cc9\' src=\'images/6-配件/_320.png\' alt=\'\'></a>");
document.writeln("									<p><a href=\'mix3.html\'>小米CC9</a></p>");
document.writeln("									<p class=\'price-cc9\'>1799元起</p>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'mix3.html\'><img class=\'xiaomi-cc9\' src=\'images/6-配件/_320.png\' alt=\'\'></a>");
document.writeln("									<p><a href=\'mix3.html\'>小米CC9</a></p>");
document.writeln("									<p class=\'price-cc9\'>1799元起</p>");
document.writeln("								</li>");
document.writeln("								<li>");
document.writeln("									<a href=\'mix3.html\'><img class=\'xiaomi-cc9\' src=\'images/6-配件/_320.png\' alt=\'\'></a>");
document.writeln("									<p><a href=\'mi9.html\'>小米CC9</a></p>");
document.writeln("									<p class=\'price-cc9\'>1799元起</p>");
document.writeln("								</li>");
document.writeln("							</ul>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</li>");
document.writeln("		        <li><a href=\'#\'>红米</a></li>");
document.writeln("		        <li><a href=\'#\'>平板 · 笔记本</a></li>");
document.writeln("		        <li><a href=\'#\'>电视</a></li>");
document.writeln("		        <li><a href=\'#\'>盒子 · 影音</a></li>");
document.writeln("		        <li><a href=\'#\'>路由器</a></li>");
document.writeln("		        <li><a href=\'#\'>智能硬件</a></li>");
document.writeln("		        <li><a href=\'#\'>服务</a></li>");
document.writeln("		        <li><a href=\'#\'>社区</a></li>");
document.writeln("		    </ul>");
document.writeln("		    <div class=\'search\'>");
document.writeln("		        <div class=\'hotwords\'>");
document.writeln("		            <a href=\'#\'>小米9</a>");
document.writeln("		            <a href=\'#\'>小米CC9</a>");
document.writeln("		        </div>");
document.writeln("		        <input type=\'search\'>");
document.writeln("		        <input type=\'submit\' value=\'&#xe605;\'>");
document.writeln("		    </div>");
document.writeln("		</div>");
document.writeln("");
document.writeln("");
document.writeln("	</body>");
document.writeln("</html>");
document.writeln("");